### ISSUE TITLE
Configuration panel is not loading

### ISSUE THREAD

**Issue by V1pr** [vwout/hass-zkaccess_c3#4]
Hi,

I'm trying to manually install the addon under homeassistant 2023.5.4. I've copied the files under custom_component, restarted HA and wanted to add the intergration, but I'm getting:

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

Relevant HA log:

 2023-12-15 13:23:47.367 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration zkaccess_c3: cannot import name '_DataT' from 'homeassistant.helpers.update_coordinator' (/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py)

Logger/logs/C3 is set to debug. Same for the 0.0.5 release and the current branch. The ZKT will be a C3-100, once the installer starts up.

**Comment by vwout** [comment]
Thanks for the report; that is exactly what I fixed in d9caebc and reverted in 9c054fb because of it not working as reported in #2. It's probably related to a change in HA. I'll investigate it.

**Comment by vwout** [comment]
Issue is hopefully finally resolved in 220e395 (but references the wrong ticket due to a typo)
