### ISSUE TITLE
Invert alarm sensor state

### ISSUE THREAD

**Issue by stepsolar** [vwout/hass-zkaccess_c3#9]
Hi, would it be possible to add the possibility of inverting the state of the alarm sensor?  Let me explain, I bought 2 magnetic sensors and they work when the door is closed the alarm is activated.  Alarm must be activated when the door is open.  Can it be reversed in programming?  Thank you

**Comment by vwout** [comment]
The zkaccess library follows the door state as represented by the access control panel. This door state is determined based on the door sensor configuration of the panel. When you configure the door sensor as NO (Normally Open) or NC (Normally Closed), the door state will be as you want.
